### ISSUE TITLE
File size in notification

### ISSUE THREAD

**Issue by terrorbobo** [mmcdole/sonarr-telegram-notifier#1]
Is it possible to display file size in the notification? Cant seem to find it in the readme. If it isnt implemented yet could you add it?

For the rest this script is working fine for me. Thanks for making this :)

**Comment by mmcdole** [comment]
@terrorbobo I've added 2 new custom variables:

```sonarr_episodefile_friendlysize``` ```sonarr_episodefile_size```

I've pushed a new release and updated the default config.json to show the friendly file size as well.
